services:
  mongodb:
    image: mongo:5.0
    container_name: mongotest2
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
